#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  >&2 echo "ERROR! YOU ARE ATTEMPTING TO COMMIT DIRECTLY TO MAIN!"
  exit 1
fi

type_error_msg="ES LINT ERRORS FOUND. Please fix them before committing. This may be because you installed a new version of a dependency including a breaking change."

yarn lint || (echo "$type_error_msg" && exit 1)

